<?php
add_action( 'admin_post_nopriv_omnius_post', 'func_omnius_post' );
add_action( 'admin_post_omnius_post', 'func_omnius_post' );

function func_omnius_post(){
    
  if ( ! function_exists( 'wp_handle_upload' ) ) {
    require_once( ABSPATH . 'wp-admin/includes/file.php' );
  }
  
  $uploadedfile = $_FILES['file'];
  $uploadedfile2 = $_FILES['file2'];
  
  $upload_overrides = array( 'test_form' => false );
  
  $movefile[] = wp_handle_upload( $uploadedfile, $upload_overrides );
  $movefile[] = wp_handle_upload( $uploadedfile2, $upload_overrides );
  
  if ( $movefile && ! isset( $movefile['error'] ) ) {
    echo "File is valid, and was successfully uploaded.\n";
    var_dump( $movefile );
  } else {
    /**
     * Error generated by _wp_handle_upload()
     * @see _wp_handle_upload() in wp-admin/includes/file.php
     */
    echo $movefile['error'];
  }
  
    global $wpdb;
    $wpdb->query(
        $wpdb->prepare(
            "insert into wp_test (wr1, wr2) values (%s,%d)",
            $_POST['wr1'],(int)$_POST['wr2']
        )
    );
    // echo "<script>alert('ok');location.href='http://localhost/wordpress';</script>";
}

?>